million/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('million_songs/', include('million_songs.urls'))
]

million_songs/urls.py
from django.urls import path

from million_songs import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('view', views.view, name='view')
]

million_songs/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class CdSeries(models.Model):
    name = models.CharField(unique=True, max_length=100)

    class Meta:
        db_table = 'cd_series'
        ordering = ['id']

    def __str__(self):
        return self.name


class CdSongs(models.Model):
    cd = models.ForeignKey('Cds', models.DO_NOTHING, blank=True, null=True)
    song = models.ForeignKey('Songs', models.DO_NOTHING, blank=True, null=True)
    unit = models.ForeignKey('Units', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        db_table = 'cd_songs'
        ordering = ['id']


class Cds(models.Model):
    name = models.CharField(unique=True, max_length=100)
    series = models.ForeignKey(CdSeries, models.DO_NOTHING)
    release_date = models.DateField()

    class Meta:
        db_table = 'cds'
        ordering = ['id']

    def __str__(self):
        return self.name


class Characters(models.Model):
    name = models.CharField(unique=True, max_length=100)
    element = models.ForeignKey('Elements', models.DO_NOTHING)

    class Meta:
        db_table = 'characters'
        ordering = ['id']

    def __str__(self):
        return self.name


class Elements(models.Model):
    name = models.CharField(unique=True, max_length=100)

    class Meta:
        db_table = 'elements'
        ordering = ['id']

    def __str__(self):
        return self.name


class Songs(models.Model):
    title = models.CharField(max_length=100)

    class Meta:
        db_table = 'songs'
        ordering = ['id']

    def __str__(self):
        return self.title


class UnitMembers(models.Model):
    member = models.ForeignKey(Characters, models.DO_NOTHING)
    unit = models.ForeignKey('Units', models.DO_NOTHING)

    class Meta:
        db_table = 'unit_members'
        ordering = ['id']
        unique_together = (('unit', 'member'),)


class Units(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    is_everyone = models.BooleanField()

    class Meta:
        db_table = 'units'
        ordering = ['id']

    def __str__(self):
        return self.name


class WholeIdView(models.Model):
    cd_series_id = models.IntegerField(blank=True, null=True)
    cd_series_name = models.CharField(max_length=100, blank=True, null=True)
    cd_id = models.IntegerField(blank=True, null=True)
    cd_name = models.CharField(max_length=100, blank=True, null=True)
    release_date = models.DateField(blank=True, null=True)
    cd_song_id = models.IntegerField(blank=True, null=True)
    song_id = models.IntegerField(blank=True, null=True)
    song_title = models.CharField(max_length=100, blank=True, null=True)
    unit_id = models.IntegerField(blank=True, null=True)
    unit_name = models.CharField(max_length=100, blank=True, null=True)
    is_everyone = models.BooleanField(blank=True, null=True)
    unit_member_id = models.IntegerField(blank=True, null=True)
    singer_id = models.IntegerField(blank=True, null=True)
    singer_name = models.CharField(max_length=100, blank=True, null=True)
    element_id = models.IntegerField(blank=True, null=True)
    element_name = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False  # Created from a view. Don't remove.
        db_table = 'whole_id_view'
        ordering = ['id']

million_songs/forms.py
from datetime import date

from django import forms

from million_songs.models import Characters, CdSeries, Cds, Units, Songs


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Characters
        fields = '__all__'
        labels = {
            'name': '名前',
            'element': '属性'
        }


class CdSeriesForm(forms.ModelForm):
    class Meta:
        model = CdSeries
        fields = '__all__'
        labels = {
            'name': '名前'
        }


class CdsForm(forms.ModelForm):
    class Meta:
        model = Cds
        fields = '__all__'
        labels = {
            'series': 'CDシリーズ',
            'name': '名前',
            'release_date': '発売日'
        }
        widgets = {
            'release_date': forms.SelectDateWidget(years=[x for x in range(2013, date.today().year)])
        }


class UnitForm(forms.Form):
    name = forms.CharField(label='ユニット名', max_length=100, required=True)
    is_everyone = forms.BooleanField(label='全体ユニット', required=False)
    unit_members = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, required=True,
                                             choices=lambda: [(character.id, character.name)
                                                              for character in Characters.objects.all()],
                                             label='ユニットメンバー')


class SongForm(forms.Form):
    cd = forms.ModelChoiceField(label='CD名', required=True, queryset=Cds.objects.all())
    is_existing_song = forms.BooleanField(label='既存曲を登録', required=False)
    title = forms.CharField(label='タイトル', max_length=100, required=False)
    existing_song = forms.ModelChoiceField(label='タイトル', required=False, queryset=Songs.objects.all())
    has_unit_name = forms.BooleanField(label='ユニット名あり', required=False)
    unit = forms.ModelChoiceField(label='ユニット名', required=False, queryset=Units.objects.filter(name__isnull=False))
    singers = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, required=False,
                                        choices=lambda: [(character.id, character.name)
                                                         for character in Characters.objects.all()],
                                        label='歌手')


class SearchForm(forms.Form):
    free = forms.CharField(label='フリー検索', required=False)
    is_title_only = forms.BooleanField(label='曲名のみで検索', required=False)
    cd = forms.ModelChoiceField(label='CD名', required=False, queryset=Cds.objects.all())
    unit = forms.ModelChoiceField(label='ユニット名', required=False, queryset=Units.objects.filter(name__isnull=False))
    singers = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, required=False,
                                        choices=lambda: [(character.id, character.name)
                                                         for character in Characters.objects.all()],
                                        label='歌手')
    is_or_search = forms.BooleanField(label='or検索', required=False)

million_songs/views.py
from django.shortcuts import render, redirect

from million_songs.entities import SingerExt, SongAll
from million_songs.forms import CharacterForm, CdSeriesForm, CdsForm, UnitForm, SongForm, SearchForm
from million_songs.models import Elements, Units, UnitMembers, Songs, WholeIdView, CdSongs


def index(request):
    elements = Elements.objects.all().order_by('id')
    return render(request, 'million_songs/index.html', {'elements': elements})


def register(request):
    params = {'character_form': None, 'cd_series_form': None, 'cds_form': None,
              'unit_form': None, 'song_form': None, 'message': None}
    if request.method == 'POST':
        if 'character_button' in request.POST:
            character_form = CharacterForm(request.POST)
            if character_form.is_valid():
                character_form.save()
                return redirect('register')
        if 'cd_series_button' in request.POST:
            cd_series_form = CdSeriesForm(request.POST)
            if cd_series_form.is_valid():
                cd_series_form.save()
                return redirect('register')
        if 'cds_button' in request.POST:
            cds_form = CdsForm(request.POST)
            if cds_form.is_valid():
                cds_form.save()
                return redirect('register')
        if 'unit_button' in request.POST:
            unit_form = UnitForm(request.POST)
            if unit_form.is_valid():
                cleaned_data = unit_form.cleaned_data
                unit = Units()
                unit.name = cleaned_data['name']
                unit.is_everyone = cleaned_data['is_everyone']
                unit.save()
                for member in cleaned_data['unit_members']:
                    unit_member = UnitMembers()
                    unit_member.unit_id = unit.id
                    unit_member.member_id = member
                    unit_member.save()
                return redirect('register')
        if 'song_button' in request.POST:
            song_form = SongForm(request.POST)
            if song_form.is_valid():
                cleaned_data = song_form.cleaned_data
                if cleaned_data['is_existing_song'] and cleaned_data['existing_song'] is None:
                    return set_field(params, request, '曲名を選んでください')
                if not cleaned_data['is_existing_song'] and cleaned_data['title'].strip() == '':
                    return set_field(params, request, '曲名を入力してください')
                cd_song = CdSongs()
                cd_song.cd_id = cleaned_data['cd'].id
                if cleaned_data['has_unit_name']:
                    if cleaned_data['unit'] is None:
                        return set_field(params, request, 'ユニットを選んでください')
                    cd_song.unit_id = cleaned_data['unit'].id
                else:
                    if len(cleaned_data['singers']) == 0:
                        return set_field(params, request, '1人以上の歌手を選んでください')
                    unit = Units()
                    unit.is_everyone = False
                    unit.save()
                    for singer in cleaned_data['singers']:
                        unit_member = UnitMembers()
                        unit_member.unit_id = unit.id
                        unit_member.member_id = singer
                        unit_member.save()
                    cd_song.unit_id = unit.id
                if cleaned_data['is_existing_song']:
                    cd_song.song_id = cleaned_data['existing_song'].id
                else:
                    song = Songs()
                    song.title = cleaned_data['title']
                    song.save()
                    cd_song.song_id = song.id
                cd_song.save()

                return redirect('register')
    params['character_form'] = CharacterForm()
    params['cd_series_form'] = CdSeriesForm()
    params['cds_form'] = CdsForm()
    params['unit_form'] = UnitForm()
    params['song_form'] = SongForm()
    return render(request, 'million_songs/register.html', params)


def set_field(params, request, message):
    params['message'] = message
    params['character_form'] = CharacterForm()
    params['cd_series_form'] = CdSeriesForm()
    params['cds_form'] = CdsForm()
    params['unit_form'] = UnitForm()
    params['song_form'] = SongForm()
    return render(request, 'million_songs/register.html', params)


def view(request):
    search_form = SearchForm(request.POST)
    whole = WholeIdView.objects.all()
    cleaned_data = None
    is_singer_search_and = False  # and検索
    is_singer_search_or = False  # or検索
    if request.method == 'POST' and search_form.is_valid():
        cleaned_data = search_form.cleaned_data
        if cleaned_data['cd'] is not None:
            whole = whole.filter(cd_id=cleaned_data['cd'].id)
        if cleaned_data['unit'] is not None:
            whole = whole.filter(unit_id=cleaned_data['unit'].id)
        if len(cleaned_data['singers']) != 0:
            if cleaned_data['is_or_search']:
                is_singer_search_or = True
            else:
                is_singer_search_and = True

    song_list = []
    song = None
    cd_id_old = 0
    song_id_old = 0
    unit_id_old = 0
    for data in whole:
        if data.cd_id != cd_id_old or data.song_id != song_id_old or data.unit_id != unit_id_old:
            song = SongAll(data.cd_series_id, data.cd_series_name, data.cd_id,
                           data.cd_name, data.release_date, data.cd_song_id, data.song_id, data.song_title,
                           data.unit_id, data.unit_name, data.is_everyone)
            song_list.append(song)
            cd_id_old = data.cd_id
            song_id_old = data.song_id
            unit_id_old = data.unit_id
        singer = SingerExt(data.singer_id, data.singer_name, data.element_id, data.element_name)
        song.singer_list.append(singer)

    if is_singer_search_or:
        for song in song_list:
            song.removed = True
            for singer in song.singer_list:
                if str(singer.id) in cleaned_data['singers']:
                    song.removed = False
                    break

    if is_singer_search_and:
        for song in song_list:
            for form_singer in cleaned_data['singers']:
                in_singer_list = False
                for singer in song.singer_list:
                    if str(singer.id) == form_singer:
                        in_singer_list = True
                if not in_singer_list:
                    song.removed = True
                    break

    return render(request, 'million_songs/view.html', {'song_list': song_list, 'search_form': search_form})

templates/million_songs/index.html
<html lang="ja">
<meta charset="UTF-8">
<head>

    <title>a</title>
</head>
<body>
<h1>おはよう</h1>
<hr>
<p style="color: red">チノちゃんもふもふ</p>
{% for element in elements %}
    <p>{{ element.name }}</p>
{% endfor %}
<a href="{% url 'register' %}">登録</a><br>
<a href="{% url 'view' %}">閲覧</a>
</body>
</html>

templates/million_songs/register.html
{% load static %}
<html lang="ja">
<meta charset="UTF-8">
<head>
    <title>登録画面</title>
    <link rel="stylesheet" href="{% static 'css/million_songs/register.css' %}">
</head>
<body>
<h1>アイドル登録</h1>
<form method="post">
    {% csrf_token %}
    {{ character_form.as_p }}
    <button type="submit" name="character_button">送信</button>
</form>
<hr>
<h1>CDシリーズ登録</h1>
<form method="post">
    {% csrf_token %}
    {{ cd_series_form.as_p }}
    <button type="submit" name="cd_series_button">送信</button>
</form>
<hr>
<h1>CD登録</h1>
<form method="post">
    {% csrf_token %}
    {{ cds_form.as_p }}
    <button type="submit" name="cds_button">送信</button>
</form>
<hr>
<h1>ユニット登録</h1>
<form method="post" style="background-color: beige">
    {% csrf_token %}
    {{ unit_form.as_p }}
    <button type="submit" name="unit_button">送信</button>
</form>
<hr>
<h1>楽曲登録</h1>
<form method="post" id="song-reg">
    {% csrf_token %}
    {% if message %}
        {{ message }}
    {% endif %}
    <p>
        {{ song_form.cd.label_tag }}
        {{ song_form.cd }}
    </p>
    <p id="is-existing-song">
        <label for="id_is_existing_song">{{ song_form.is_existing_song.label }}:</label>
        <input type="checkbox" name="is_existing_song" id="id_is_existing_song" v-model="is_existing_song">
    </p>
    <p id="title" v-if="!is_existing_song">
        {{ song_form.title.label_tag }}
        {{ song_form.title }}
    </p>
    <p id="existing-song" v-if="is_existing_song">
        {{ song_form.existing_song.label_tag }}
        {{ song_form.existing_song }}
    </p>
    <p>
        <label for="id_has_unit_name">{{ song_form.has_unit_name.label }}:</label>
        <input type="checkbox" name="has_unit_name" id="id_has_unit_name" v-model="has_unit_name">
    </p>
    <p id="unit" v-if="has_unit_name">
        {{ song_form.unit.label_tag }}
        {{ song_form.unit }}
    </p>
    <div id="singers" v-if="!has_unit_name">
        {{ song_form.singers.label_tag }}
        {{ song_form.singers }}
    </div>
    <button type="submit" name="song_button">送信</button>
    <hr>
    <div style="height: 55em" v-if="has_unit_name"></div>
</form>
<script src="https://unpkg.com/vue@next"></script>
<script>
    const SongReg = {
        data() {
            return {
                is_existing_song: false,
                has_unit_name: false
            }
        }
    }
    Vue.createApp(SongReg).mount('#song-reg')
</script>
<script src="{% static 'js/million_songs/register.js' %}"></script>
</body>
</html>

templates/million_songs/view.html
{% load static %}
<html lang="ja">
<meta charset="UTF-8">
<head>
    <title>a</title>
    <link rel="stylesheet" href="{% static 'css/million_songs/view.css' %}">
</head>
<body>
<h1>曲名一覧</h1>
<h2>検索</h2>
<form method="post" id="search">
    {% csrf_token %}
    <p>
        {{ search_form.free.label_tag }}
        {{ search_form.free }}
    </p>
    <p>
        {{ search_form.is_title_only.label_tag }}
        {{ search_form.is_title_only }}
    </p>
    <p>
        {{ search_form.cd.label_tag }}
        {{ search_form.cd }}
    </p>
    <p>
        {{ search_form.unit.label_tag }}
        {{ search_form.unit }}
    </p>
    <div>
        {{ search_form.singers.label_tag }}<br>
        <label for="id_show">表示</label>
        <input id="id_show" name="show" type="checkbox" v-model="show_singers">

        <div id="singers_value" v-if="show_singers">
            {{ search_form.singers }}
        </div>
    </div>
    <p>
        {{ search_form.is_or_search.label_tag }}
        {{ search_form.is_or_search }}
    </p>
    <button type="submit" name="unit_button">送信</button>
</form>
<hr>
<table style="border: 2px black solid">
    <tr>
        <td>CDシリーズ</td>
        <td>CD名</td>
        <td>曲名</td>
        <td>ユニット名</td>
        <td>歌手名</td>
    </tr>
    {% for song in song_list %}
        {% if song.removed == False %}
            <tr>
                <td>{{ song.cd_series_name }}</td>
                <td>{{ song.cd_name }}</td>
                <td>{{ song.song_title }}</td>
                <td>
                    {% if song.unit_name %}
                        {{ song.unit_name }}
                    {% elif song.singer_list|length == 1 %}
                    {% else %}
                        なし
                    {% endif %}
                </td>
                <td>
                    {% for singer in song.singer_list %}
                        <span style="display: inline-block">{{ singer }}</span>
                    {% endfor %}
                </td>
            </tr>
        {% endif %}
    {% endfor %}
</table>
<script src="https://unpkg.com/vue@next"></script>
<script>
    const SongSearch = {
        data() {
            return {
                show_singers: false
            }
        }
    }
    Vue.createApp(SongSearch).mount('#search')
</script>
</body>
</html>